#!/usr/bin/env zsh

clpr blue "The following commands are available:"
clpr default "${1} ps                   List running containers (docker ps)"
clpr default "${1} psa                  Lists all containers (docker ps -a)"
clpr default "${1} stopall (sa)         Stops all running containers"
clpr default "${1} rmall (ra)           Deletes all containers"
clpr default "${1} sra                  Stops and then Deletes all containers"
clpr default "${1} i                    Shows the images in docker"
clpr default "${1} li                   Shows the latest image created"
clpr default "${1} rmlatest (rml)       Shows the latest image created and asks if you want to delete it"
clpr default "${1} rlii)                Shows the latest image created and asks if you want to run it"
clpr default "${1} elci)                Exec Latest-Launched Container in Interactive mode"
clpr default ""
clpr blue "Run '${1} help' to get this help."
clpr blue "Running ${1} <command> where command is not in the above list will run 'docker <command>'."
clpr blue "    e.g. '${0} --help' will run 'docker --help'"
